version: '2'

services:
   db:
     image: postgres:9.6.2
     volumes:
       - db_data:/var/lib/postgres
     restart: always
     environment:
       POSTGRES_USER: closure
       POSTGRES_PASSWORD: shed
       POSTGRES_DB: closureshed

   closure-shed:
     depends_on:
       - db
     image: headwinds/closure-shed:latest
     ports:
       - "8000:3000"
     restart: always
     environment:
       DATABASE_URL: jdbc:postgresql://db/closureshed?user=closure&password=shed
volumes:
    db_data:
