version: '2'

services:
   db:
     image: postgres:9.6.2
     volumes:
       - db_data:/var/lib/postgres
     restart: always
     environment:
       POSTGRES_USER: clojure
       POSTGRES_PASSWORD: shed
       POSTGRES_DB: shed

   clojure-docker-postgres:
     depends_on:
       - db
     image: headwinds/clojure-docker-postgres:latest
     ports:
       - "8000:3000"
     restart: always
     environment:
       DATABASE_URL: jdbc:postgresql://db/shed?user=clojure&password=shed
volumes:
    db_data:
